osx_image: xcode11.3.1
language: swift
xcode_sdk: iphonesimulator13.3

xcode_project: ESTabBarControllerExample/ESTabBarControllerExample.xcodeproj
xcode_scheme: ESTabBarControllerExample

# whitelist
branches:
only:
- master
